// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ulhlmrjyjhrgktncggav.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVsaGxtcmp5amhyZ2t0bmNnZ2F2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3NDIwMjIsImV4cCI6MjA2MDMxODAyMn0.cfcu8PaKMNwtDQpprE4pLlSk-mEb5Acl7P--Tyq0XTc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);